# Generated by Django 5.2.16 on 2026-07-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('octa', 'Octa Wood'), ('circle', 'Cercle Tag'), ('capsule', 'Capsule Soft')], max_length=20)),
                ('material', models.CharField(choices=[('light_wood', 'Bois texture claire'), ('dark_wood', 'Bois sombre'), ('black_wood', 'Bois noire'), ('white_pvc', 'PVC blanc'), ('black_pvc', 'PVC noir')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='disks/')),
            ],
        ),
    ]
