# Generated by Django 5.2.16 on 2026-08-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracelets', '0002_ownedbracelet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedbracelet',
            name='configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
