# Generated by Django 5.2.16 on 2026-07-24 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nfc', '0002_alter_nfcprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('youtube', 'YouTube'), ('x', 'X'), ('website', 'Website')], max_length=30)),
                ('url', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='nfc.nfcprofile')),
            ],
            options={
                'unique_together': {('profile', 'platform')},
            },
        ),
    ]
