# Generated by Django 5.2.16 on 2026-07-24 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bracelets', '0002_ownedbracelet'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('profession', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('profile_image', models.ImageField(upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bracelet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='bracelets.ownedbracelet')),
            ],
        ),
    ]
