# Generated by Django 5.2.16 on 2026-07-22 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beads', '0001_initial'),
        ('bracelets', '0001_initial'),
        ('colors', '0001_initial'),
        ('disks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engraving', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beads.bead')),
                ('bracelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bracelets.bracelet')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colors.color')),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disks.disk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
